#import "@preview/ilm:2.0.0": *

#set text(lang: "en")
#set text(size: 10.5pt)

#show: ilm.with(
  title: [Project 4: Double Descent in Linear Models],
  authors: "Giacomo Comitani",
  date: datetime(year: 2026, month: 05, day: 8),
  abstract: [Historically in machine learning, models were constructed following the bias-variance trade-off, balancing under-fitting and over-fitting to obtain an optimal predictor that does not memorize the training data, but rather learns a general rule to perform well on unseen data. Classically, this implied restricting the number of features d to be strictly less than the number of examples n in the dataset, aiming to find the sweet spot at the minimum of the U-shaped test risk curve. In modern practice, however, highly complex models like neural networks routinely achieve optimal generalization results even when operating in an over-parameterized regime, strictly at or beyond the interpolation threshold (where training error is exactly zero). In their paper, Belkin et al. @belkin2019reconciling reconcile this apparent contradiction by demonstrating the "double descent" risk curve. They observed that by increasing the model capacity (d) beyond the interpolation point, predictors can achieve a second descent in test error, challenging the classical limitations of ML theory. This project aims to empirically reproduce this phenomenon using linear models. By generating a synthetic dataset with noisy linear labels, I follow their theoretical framework to observe the double descent curve and validate the mechanisms described by the authors],
  table-of-contents: none,
  bibliography: bibliography("works.bib"),
)

#set page(
  header: context [
    #set text(size: 10pt)
    Giacomo Comitani -- 85673A
    #line(length: 100%, stroke: rgb("#919191"))
  ],
  footer: context [
    #line(length: 100%, stroke: rgb("#919191"))
    #set text(size: 10pt)
    University of Milan -- Department of Computer Science
    #h(1fr)
    #counter(page).display()
  ],
)

= Initial Declarations

“I declare that this material, which I now submit for assessment, is entirely my own work and has not been taken from the work of others, save and to the extent that such work has been cited and acknowledged within the text of my work. I understand that plagiarism, collusion, and copying are grave and serious offences in the university and accept the penalties that would be imposed should I engage in plagiarism, collusion or copying. This assignment, or any part of it, has not been previously submitted by me or any other person for assessment on this or any other course of study“

= Important choices

== Generation of the synthetic dataset

The first step of the project was to construct the synthetic dataset. To natively prevent data leakage, I generated the training and test sets as completely independent blocks right from the start. As highlighted by the official scikit-learn guidelines @scikitlearnCommonPitfalls, splitting the data into independent training and test subsets must always be the very first step before any processing. This strict separation guarantees that the model has no possibility of accessing the test data during the training phase. Since the assignment gave us the freedom to design the data-generating process, I chose to sample the input features $X$ from a standard Gaussian distribution. I made this choice because it naturally gives all the features the exact same scale (mean 0 and variance 1) and keeps them independent. This way, I don't need to manually normalize the data. Following the assignment guidelines, I defined the target labels as a linear combination of these inputs: 

$ y = X w^* + epsilon $

where: 

- $y in RR^n$ represents the vector of the target labels.

- $X in RR^(n times d)$ is the matrix containing the input features, generated by sampling from a standard Gaussian distribution.

- $w^* in RR^d$ is the vector of the weights.

- $epsilon in RR^n$ is the noise vector, sampled from a Gaussian distribution with mean zero to introduce stochasticity into the observations.

During the creation of the labels, I introduced noise to simulate a realistic scenario. This noise was again sampled from a Gaussian distribution. To prevent data leakage, the noise vectors for the training and the test sets were generated via two separate calls. Reusing the same noise for training and test would violate the i.i.d. assumption, creating a situation in which test labels are mathematically correlated with training labels @data-leakage.

Finally, I implemented a fixed seed for the random number generator. A core requirement of this project is reproducibility; the seed acts as a deterministic starting point for the pseudo-random numbers, ensuring that the exact same dataset and results can be perfectly replicated multiple times and on different machines @JMLR:v22:20-303. Without the seed, the process of generating random numbers would initialize at a different state during every execution (typically using the machine's internal clock as a starting point), making it impossible to obtain a perfect replica of the work on different machines.
